version: '3.7'

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"    # Important: In a production environment your should remove the external port
      
  mobileorderer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Config:ConnectionString=Server=sql.data,1433;Initial Catalog=Mobile;User Id=MobileOrdererMicroservice;Password=MobileOrderer@123
      - EventBusConfig:SnsServiceUrl=http://goaws:4100
      - EventBusConfig:SqsServiceUrl=http://goaws:4100
    ports:
      - "5000:80"
 
  simcards.eventhandlers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Config:ConnectionString=Server=sql.data,1433;Initial Catalog=Mobile;User Id=SimCardsMicroservice;Password=SimCards@123
      - Config:SimCardWholesalerApiUrl=http://simcardwholesaler.api
      - EventBusConfig:SnsServiceUrl=http://goaws:4100
      - EventBusConfig:SqsServiceUrl=http://goaws:4100
     
  simcardwholesaler.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Config:ConnectionString=Server=sql.data,1433;Initial Catalog=Mobile;User Id=SimCardWholesalerWebService;Password=SimCardWholesaler@123
    ports:
      - "5001:80"
  