version: '3.7'

volumes:
    prometheus_data: {}
    
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:7.0.6
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000

  sql.data:
    image: mcr.microsoft.com/mssql/server
    build:
      context: .
      dockerfile: DatabaseSetup/Dockerfile

  goaws:
    image: pafortin/goaws
    ports:
      - "4100:4100"
      
  mobileorderer.api:
    image: ${DOCKER_REGISTRY}mobileordererapi
    build:
      context: .
      dockerfile: src/MobileOrderer/MobileOrderer.Api/Dockerfile

  simcards.eventhandlers:
    image: ${DOCKER_REGISTRY}simcardseventhandlers
    build:
      context: .
      dockerfile: src/SimCards/SimCards.EventHandlers/Dockerfile
    stdin_open: true
    tty: true

  externalsimcardsprovider.api:
    image: ${DOCKER_REGISTRY}externalsimcardsproviderapi
    build:
      context: .
      dockerfile: src/ExternalSimCardsProvider/ExternalSimCardsProvider.Api/Dockerfile

  mobiletelecomsnetwork.eventhandlers:
    image: ${DOCKER_REGISTRY}mobiletelecomsnetworkhandlers
    build:
      context: .
      dockerfile: src/MobileTelecomsNetwork/MobileTelecomsNetwork.EventHandlers/Dockerfile
    stdin_open: true
    tty: true
    
  externalmobiletelecomsnetwork.api:
    image: ${DOCKER_REGISTRY}externalmobiletelecomsnetwork
    build:
      context: .
      dockerfile: src/ExternalMobileTelecomsNetwork/ExternalMobileTelecomsNetwork.Api/Dockerfile
  