version: '3.7'

# volumes:
#     prometheus_data: {}
    
services:
  goaws:
    image: pafortin/goaws
    ports:
      - "4100:4100"
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80

  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus/:/etc/prometheus/
  #     - ./prometheus_data/:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #   ports:
  #     - 9090:9090

  # grafana:
  #   image: grafana/grafana:7.0.6
  #   volumes:
  #     - ./grafana_data:/var/lib/grafana
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
  #     - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   ports:
  #     - 3000:3000

  
  