version: '3.7'

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"    # Important: In a production environment your should remove the external port
      
  mobileorderer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Config:LogFilePath=/logs/
      - Config:ConnectionString=Server=sql.data,1433;Initial Catalog=Mobile;User Id=MobileOrdererMicroservice;Password=MobileOrderer@123
      - Config:SeqUrl=http://seq:5341
      - EventBusConfig:SnsServiceUrl=http://goaws:4100
      - EventBusConfig:SqsServiceUrl=http://goaws:4100
    ports:
      - "5000:80"

  simcards.eventhandlers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Config:LogFilePath=/logs/
      - Config:ConnectionString=Server=sql.data,1433;Initial Catalog=Mobile;User Id=SimCardsMicroservice;Password=SimCards@123
      - Config:ExternalSimCardsProviderApiUrl=http://externalsimcardsprovider.api
      - Config:SeqUrl=http://seq:5341
      - EventBusConfig:SnsServiceUrl=http://goaws:4100
      - EventBusConfig:SqsServiceUrl=http://goaws:4100
      
  externalsimcardsprovider.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Config:ConnectionString=Server=sql.data,1433;Initial Catalog=Mobile;User Id=ExternalSimCardsProviderWebService;Password=ExternalSimCardsProvider@123
      - Config:ExternalSimCardsProviderApiUrl=http://externalsimcardsprovider.api
    ports:
      - "5001:80"
      
  mobiletelecomsnetwork.eventhandlers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Config:LogFilePath=/logs/
      - Config:ConnectionString=Server=sql.data,1433;Initial Catalog=Mobile;User Id=MobileTelecomsNetworkMicroservice;Password=MobileTelecomsNetwork@123
      - Config:ExternalMobileTelecomsNetworkApiUrl=http://externalmobiletelecomsnetwork.api
      - Config:SeqUrl=http://seq:5341
      - EventBusConfig:SnsServiceUrl=http://goaws:4100
      - EventBusConfig:SqsServiceUrl=http://goaws:4100
      
  externalmobiletelecomsnetwork.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Config:ConnectionString=Server=sql.data,1433;Initial Catalog=Mobile;User Id=ExternalMobileTelecomsNetworkWebService;Password=ExternalMobileTelecomsNetwork@123
    ports:
      - "5002:80"