
###==================================================
### Mobile Orderer
###==================================================

### Health Check
GET http://localhost:5000/api/provisioner/status

### Order a Mobile
POST http://localhost:5000/api/provisioner
content-type: application/json

{
	"Name" : "Neil Armstrong",
	"ContactPhoneNumber" : "00123456789"
}

### Get an Order
GET http://localhost:5000/api/provisioner/2F8326D3-EFD1-4D30-99D3-E2FA75BC7CEF

###==================================================
### SimCard Wholesaler
###==================================================

### Health check
GET http://localhost:5001/api/orders/status

### Create an Order
POST http://localhost:5001/api/orders
content-type: application/json

{
	"Reference" : "CF94A4CA-7CAD-467B-946C-ED4642280033",
	"Name" : "Neil Armstrong",
}

### Get an Order
GET http://localhost:5001/api/orders/D651B45D-EE98-4CD4-BC74-C97C466600D6

### Complete an Order
POST http://localhost:5001/api/orders/complete
content-type: application/json

{
	"Reference" : "11D3C42D-46A7-41CB-8DB3-3B6A334A29ED"
}
