
###
### Sceanrio 1. Order a Mobile
###

### Step 1 - Order a Mobile
POST http://localhost:5000/api/provisioner
content-type: application/json

{
	"Name" : "Neil Armstrong",
	"ContactPhoneNumber" : "00123456789"
}

### Get the Mobile, so we can get the Order Reference (orderHistory.globalId)
GET http://localhost:5000/api/mobiles/F435B4A8-98E4-44BF-BB43-F0A3A0CB12AE

### Step 2 - Mobile Provision Order has been Completed
POST http://localhost:5001/api/orders/DC2BAC81-01D0-4DD1-9F11-612B114CAC26/complete

### Step 3 - Activate a Mobile
POST http://localhost:5000/api/mobiles/B32528CD-30CB-4625-90EF-AD77D629B04D/activate
content-type: application/json

{
	"Name" : "Neil Armstrong",
	"ContactPhoneNumber" : "00123456789"
}

### Step  4 - Mobile Activate Order has been Completed
POST http://localhost:5002/api/orders/CAFA8CF9-CF1A-441B-8CB3-9C2C4C7DA02E/complete

###
### Sceanrio 2. Cease a Mobile
###

### Step 1 - Cease a Mobile
DELETE http://localhost:5000/api/mobiles/714C0D05-DF75-4FBB-83BA-CE68B943DA0D

### Step 2 - Cease Order has been Completed
POST http://localhost:5002/api/orders/AEC96534-179B-4C91-8AA3-C4309B191A7B/complete