
###
### Scenario 1. Order a Mobile
###

### Step 1 - Create a Customer
# @name createCustomer
POST http://localhost:5000/api/customers
content-type: application/json

{
	"Name" : "Armstrong Corporation"
}

###
@customerId = {{createCustomer.response.body.$.globalId}}

### Step 2 - Order a Mobile
# @name orderMobile
POST http://localhost:5000/api/customers/{{customerId}}/provision
content-type: application/json

{
	"Name" : "Neil Armstrong",
	"ContactPhoneNumber" : "00123456789"
}

###
@mobileId = {{orderMobile.response.body.$.globalId}}

### Get the Mobile, so we can get the Order Reference (orderHistory.globalId)
# @name getOrder
GET http://localhost:5000/api/mobiles/{{mobileId}}

###
@orderId = {{getOrder.response.body.$.orderHistory.$[0].globalId}}

### Step 3 - Mobile Provision Order has been Completed
POST http://localhost:5001/api/orders/{{orderId}}/complete

### Step 4 - Activate a Mobile
# @name activateMobile
POST http://localhost:5000/api/mobiles/{{mobileId}}/activate
content-type: application/json

{
	"Name" : "Neil Armstrong",
	"ContactPhoneNumber" : "00123456789"
}
###
@activateOrderId = {{activateMobile.response.body.$.globalId}}


### Step  5 - Mobile Activate Order has been Completed
POST http://localhost:5002/api/orders/{{activateOrderId}}/complete

###
### Scenario 2. Cease a Mobile
###

### Step 1 - Cease a Mobile
DELETE http://localhost:5000/api/mobiles/{{mobileId}}

### Get the Mobile, so we can get the Order Reference (orderHistory.globalId)
# @name getCeaseOrder
GET http://localhost:5000/api/mobiles/{{mobileId}}

###
@ceaseOrderId = {{getCeaseOrder.response.body.$.orderHistory[?(@.type==2)].globalId}}

### Step 2 - Cease Order has been Completed
POST http://localhost:5002/api/orders/{{ceaseOrderId}}/complete

