
###==================================================
### Monitoring
###==================================================

### Prometheus Dashboard
http://localhost:9090

### Grafana Dashboard
GET localhost:3000

### Docker Workers
GET 192.168.65.1:9323/metrics

###==================================================
### Mobiles
###==================================================

### Health Check
GET http://localhost:5000/health

### Get Prometheus metrics
GET http://localhost:5000/metrics

### Get Customers
GET http://localhost:5000/api/customers

### Create a Customer
POST http://localhost:5000/api/customers
content-type: application/json

{
	"Name" : "Armstrong Corporation"
}

### Get a Customer
GET http://localhost:5000/api/customers/c856f7ae-cfc8-4786-8cbd-4d77f7987bd4


### Order a Mobile
POST http://localhost:5000/api/customers/a4ba8933-5754-44d8-9068-b2b698af3d6f/provision
content-type: application/json

{
	"PhoneNumber": "07777000001",
	"Name" : "Neil Armstrong",
	"ContactPhoneNumber" : "00123456789"
}

### Get a Mobile
GET http://localhost:5000/api/mobiles/5acbde4c-62ed-4a3f-b415-2388e6a2b563

### Activate a Mobile
POST http://localhost:5000/api/mobiles/6F04C7C5-2D23-4D9A-A2B6-575B452C8ACF/activate
content-type: application/json

{
	"ActivationCode": "ZZZYHB163"
}

### Cease a Mobile
DELETE http://localhost:5000/api/mobiles/C0674BE0-AD47-44A4-A2D3-9EA9B387923D

###==================================================
### ExternalSimCardsProvider
###==================================================

### Health check
GET http://localhost:5001/health

### Create an Order
POST http://localhost:5001/api/orders
content-type: application/json

{
	"Reference" : "CF94A4CA-7CAD-467B-946C-ED4642280033",
	"Name" : "Neil Armstrong",
}

### Get an Order
GET http://localhost:5001/api/orders/7783E7B1-98F1-4064-853C-D1FE5808CE1B

### Complete an Order
POST http://localhost:5001/api/orders/6C1622FB-70FB-4A02-89F2-780AF670149E/complete

###==================================================
### ExternalMobileTelecomsNetwork.Api
###==================================================

### Health check
GET http://localhost:5002/health

### Create an Order
POST http://localhost:5002/api/orders
content-type: application/json

{
	"Reference" : "CF94A4CA-7CAD-467B-946C-ED4642280033",
	"Name" : "Neil Armstrong"
}

### Get an Order
GET http://localhost:5002/api/orders/7783E7B1-98F1-4064-853C-D1FE5808CE1B

### Complete an Order
POST http://localhost:5002/api/orders/FDAA0F93-ADAA-4A20-B6D1-48255CE28B3E/complete