
###==================================================
### Monitoring
###==================================================

### Prometheus Dashboard
http://localhost:9090

### Grafana Dashboard
GET localhost:3000

### Docker Workers
GET 192.168.0.5:9323/metrics

### Seq running in docker
GET http://192.168.0.5:5341

### goaws running in docker
GET http://192.168.56.101:4100

### Check goaws queues
POST http://192.168.0.5:4100/
Authorization:AL03THI20QLMNG01QOPU5EDS/ftg7tCesw0Yr%Xr%3jV2KOyKaoLzZXre3sIAWOI8
Content-Type:multipart/form-data; boundary=--------------------------669459213080013617420231

----------------------------669459213080013617420231
Content-Disposition: form-data; name="Action"

ListQueues
----------------------------669459213080013617420231
Content-Disposition: form-data; name="Version"

2012-11-05
----------------------------669459213080013617420231--

### Check a queue(ActivateRequested)
POST http://192.168.0.5:4100/ActivateRequested?Action=GetQueueAttributes
Authorization:AL03THI20QLMNG01QOPU5EDS/ftg7tCesw0Yr%Xr%3jV2KOyKaoLzZXre3sIAWOI8
Content-Type:multipart/form-data; boundary=--------------------------669459213080013617420231

----------------------------669459213080013617420231
Content-Disposition: form-data; name="Action"

ListQueues
----------------------------669459213080013617420231
Content-Disposition: form-data; name="Version"

2012-11-05
----------------------------669459213080013617420231--

###==================================================
### Mobiles
###==================================================

### Health Check
GET http://localhost:5000/health

### Get Prometheus metrics
GET http://localhost:5000/metrics

### Get Customers
GET http://localhost:5000/api/customers

### Create a Customer
POST http://localhost:5000/api/customers
content-type: application/json

{
	"Name" : "Armstrong Corporation"
}

### Get a Customer
GET http://localhost:5000/api/customers/C5C04D13-25B2-4EC2-97E0-99737673287F


### Order a Mobile
POST http://localhost:5000/api/customers/11A2CD6B-5911-4407-84E8-6812B5AD12E0/provision
content-type: application/json

{
	"PhoneNumber": "07777000001",
	"Name" : "Neil Armstrong",
	"ContactPhoneNumber" : "00123456789"
}

### Get a Mobile
GET http://localhost:5000/api/mobiles/422DD8B1-BD6E-4594-8958-D8DC60D495B1

### Get a Mobile ActivationCode
GET http://localhost:5001/api/orders/247AB73E-8FA2-4177-A9EC-2AE072A82029/activationCode

### Activate a Mobile
POST http://localhost:5000/api/mobiles/6F04C7C5-2D23-4D9A-A2B6-575B452C8ACF/activate
content-type: application/json

{
	"ActivationCode": "ZZZYHB163"
}

### Cease a Mobile
DELETE http://localhost:5000/api/mobiles/C0674BE0-AD47-44A4-A2D3-9EA9B387923D

### Get available Phone Numbers
GET http://localhost:5000/api/mobiles/availablePhoneNumbers

###==================================================
### ExternalSimCardsProvider
###==================================================

### Health check
GET http://localhost:5001/health

### Create an Order
POST http://localhost:5001/api/orders
content-type: application/json

{
	"Reference" : "CF94A4CA-7CAD-467B-946C-ED4642280033",
	"Name" : "Neil Armstrong",
}

### Get an Order
GET http://localhost:5001/api/orders/7783E7B1-98F1-4064-853C-D1FE5808CE1B

### Complete an Order
POST http://localhost:5001/api/orders/247AB73E-8FA2-4177-A9EC-2AE072A82029/complete

###==================================================
### ExternalMobileTelecomsNetwork.Api
###==================================================

### Health check
GET http://localhost:5002/health

### Create an Order
POST http://localhost:5002/api/orders
content-type: application/json

{
	"Reference" : "CF94A4CA-7CAD-467B-946C-ED4642280033",
	"Name" : "Neil Armstrong"
}

### Get an Order
GET http://localhost:5002/api/orders/7783E7B1-98F1-4064-853C-D1FE5808CE1B

### Complete an Order
POST http://localhost:5002/api/orders/FDAA0F93-ADAA-4A20-B6D1-48255CE28B3E/complete

###==================================================

http://localhost:5000/api/mobiles/9db84c57-218a-4f22-88a3-fdb116a585a6