global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: mobiles
    static_configs:
      - targets: ["mobileorderer.api"]
        labels:
          alias: "mobileorderer.api"

  - job_name: simcards
    static_configs:
      - targets: ["simcards.eventhandlers"]
        labels:
          alias: "simcards.eventhandlers"
