global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: mobiles
    static_configs:
      - targets: ["mobiles.api"]
        labels:
          alias: "mobiles.api"

  - job_name: simcards
    static_configs:
      - targets: ["simcards.eventhandlers:6080"]
        labels:
          alias: "simcards.eventhandlers"

  - job_name: mobiletelecomsnetwork
    static_configs:
      - targets: ["mobiletelecomsnetwork.eventhandlers:6081"]
        labels:
          alias: "mobiletelecomsnetwork.eventhandlers"

  - job_name: 'docker-workers'
    static_configs:
      - targets: ["host.docker.internal:9323"]