{
 "title": "Mobile System Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Provisions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mobile_provisions" }
   ]
  },
  {
   "title": "Activates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mobile_activates" }
   ]
  },
  {
   "title": "Ceases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mobile_ceases" }
   ]
  }
 ]
}