@startuml
'!includeurl https://raw.githubusercontent.com/kirchsth/C4-PlantUML/master/C4_Dynamic.puml
' uncomment the following line and comment the first to use locally
!include C4_Dynamic.puml

LAYOUT_TOP_DOWN
LAYOUT_WITH_LEGEND()

title Activate a Mobile
Person(customer, "Customer", "A Customer orders a Mobile.")

System_Boundary(c1, "Mobile System") {
    Container(web_app, "Mobile Orderer Web Application", "C#, ASP.NET Core", "")

    Container(mobiles_ms, "Mobiles Microservice", "C#, ASP.NET Core", "")    
    Container(mobile_network_ms, "Mobile Telecoms Network Microservice", "C#, ASP.NET Core", "")
    
    ContainerDb(mobiles_db, "Mobiles database", "SQL Server", "")    
    ContainerDb(mobile_network_db, "Mobile Telecoms Network database", "SQL Server", "")    
}

System_Ext(mobile_telecoms_network_system, "Mobile Telecoms Network system", "The external Mobile Telecoms Network system.")

Interact(customer, web_app, "Activate a Mobile", "HTTPS")
Interact(web_app, mobiles_ms, "Posts Activation Order", "HTTPS")
Interact2_Right("GetIndex(0)-1", mobiles_ms, mobiles_db, "Writes new Mobile+Activation Order", "EF")
Interact2("GetIndex()-2", mobiles_ms, mobile_network_ms, "Posts Activation Order", "HTTPS")
Interact2_Right("GetIndex(0)-1", mobile_network_ms, mobile_network_db, "Writes new Activation Order", "Dapper")
Interact2("GetIndex()-2", mobile_network_ms, mobile_telecoms_network_system, "Posts Activation Order", "HTTPS")

Interact2_Right("GetIndex(0)-1", mobile_network_ms, mobile_network_db, "Updates Activation Order to Sent", "Dapper")
Interact2("GetIndex()-2", mobile_network_ms, mobiles_ms, "Publishes Activation Order Sent", "AWS SNS+SQS/JSON")
'
Interact_Right(mobiles_ms, mobiles_db, "Updates Activation Order to Sent", "EF")

@enduml